# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import article_pb2 as article__pb2
from . import article_pb2 as article__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in article_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArticleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ArticleList = channel.unary_unary(
                '/ArticleService/ArticleList',
                request_serializer=article__pb2.ArticleListRequest.SerializeToString,
                response_deserializer=article__pb2.ArticleListResponse.FromString,
                _registered_method=True)
        self.ArticleDetail = channel.unary_unary(
                '/ArticleService/ArticleDetail',
                request_serializer=article__pb2.ArticleDetailRequest.SerializeToString,
                response_deserializer=article__pb2.ArticleDetailResponse.FromString,
                _registered_method=True)
        self.CreateArticle = channel.unary_unary(
                '/ArticleService/CreateArticle',
                request_serializer=article__pb2.CreateArticleRequest.SerializeToString,
                response_deserializer=article__pb2.CreateArticleResponse.FromString,
                _registered_method=True)
        self.UpdateArticle = channel.unary_unary(
                '/ArticleService/UpdateArticle',
                request_serializer=article__pb2.UpdateArticleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteArticle = channel.unary_unary(
                '/ArticleService/DeleteArticle',
                request_serializer=article__pb2.DeleteArticleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ArticleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ArticleList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArticleDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ArticleList': grpc.unary_unary_rpc_method_handler(
                    servicer.ArticleList,
                    request_deserializer=article__pb2.ArticleListRequest.FromString,
                    response_serializer=article__pb2.ArticleListResponse.SerializeToString,
            ),
            'ArticleDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.ArticleDetail,
                    request_deserializer=article__pb2.ArticleDetailRequest.FromString,
                    response_serializer=article__pb2.ArticleDetailResponse.SerializeToString,
            ),
            'CreateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArticle,
                    request_deserializer=article__pb2.CreateArticleRequest.FromString,
                    response_serializer=article__pb2.CreateArticleResponse.SerializeToString,
            ),
            'UpdateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticle,
                    request_deserializer=article__pb2.UpdateArticleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArticle,
                    request_deserializer=article__pb2.DeleteArticleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArticleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ArticleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArticleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ArticleList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ArticleService/ArticleList',
            article__pb2.ArticleListRequest.SerializeToString,
            article__pb2.ArticleListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArticleDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ArticleService/ArticleDetail',
            article__pb2.ArticleDetailRequest.SerializeToString,
            article__pb2.ArticleDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ArticleService/CreateArticle',
            article__pb2.CreateArticleRequest.SerializeToString,
            article__pb2.CreateArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ArticleService/UpdateArticle',
            article__pb2.UpdateArticleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ArticleService/DeleteArticle',
            article__pb2.DeleteArticleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
